logger:
  enabled: true
  level: info # debug, info, warn, error
  format: json # json, console
  output: stdout # stdout, file
  path: ./logs/app.log
  max_size: 100 # megabytes
  max_backups: 7
  max_age: 30 # days
  compress: true # disabled by default

database:
  db-0:
    enabled: true
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: ${POSTGRES_DOCKER_PASSWORD}
    dbname: go-kill-user
    sslmode: false

queries:
  path: ./etc/sql/

mongo:
  mongo-0:
    host: localhost
    port: 27017
    database: "go-kill"
    username: ""
    password: ""
    auth_source: ""
    timeout: 10s

scheduler:
  job-0:
    enabled: true
    name: user-generator
    cron: "*/30 * * * * *" # Every 30 seconds
    batch_size: 5

grpc_client:
  auth_service:
    target: "localhost:8081"
    timeout: 5s
    insecure: true

grpc_server:
  port: ":8082"
  shutdown_timeout: 10s

http:
  app_name: "User Service"

server:
  port: 8083
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
